name: Step 1, Create a workflow

# This step triggers after every push to welcome-workflow
# This step sets STEP to 2
# This step closes <details id=1> and opens <details id=2>   이 단계에서는 <detail id=1>를 닫고<detail id=2>를 엽니다.

# This will run every time we push to welcome-workflow
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - welcome-workflow

# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository  / 저장소를 체크아웃하려면 'content:read' 가 있어야하고
  # Need `contents: write` to update the step metadata  /단계 메타 데이터(script/STEP)를 업데이트하려면 '내용: 쓰기' 가 필요합니다.
  contents: write

jobs:
  on_create_workflow:
    name: On create workflow

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ !github.event.repository.is_template }}  # repository 가 template 가 아닐 경우

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README   / README를 편집하기 위해서 저장소를 체크 아웃합니다
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches

      # Verify the learner added the file contents  # 학습자가 파일 콘텐츠를 추가했는지 확인 
      - name: Check workflow contents, name
        run: ./.github/script/check-file.sh 
        env:
          FILE: ".github/workflows/welcome.yml"
          SEARCH: "name:"

      # Update README to close <details id=1> and open <details id=2>
      # and set STEP to '2'
      - name: Update to step 2
        uses: skills/action-update-step@v1  
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2
          branch_name: welcome-workflow
