name: Our Steps
on: push
jobs: 
  foobar:
    runs-on: ubuntu-latest
    steps:
      - id: set-foo
        run: echo "::set-output name=foo::bar"
      - run: echo ${{ steps.set-foo.outputs.foo }}




# step은 순차적으로 수행되기 때문에 이전 단계에서 발생한 결과물을 다음 단계로 전달하는 것이 가능합니다.
# 즉, 어떤 단계에서 특정 값을 출력으로 내보내면 그 단계 이후로 실행되는 모든 단계에서 해당 출력 값을 불러올 수 있습니다.
