name: Reusable Workflow

on:
  push:
  workflow_call:   #이 workflow_call 이 있어야만 재사용이 가능함
    inputs:
      username:
        required: true
        type: string
    secrets:
      SECRET_SEED:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo ${{ inputs.username }}
          echo ${{ secrets.SECRET_SEED }}
          echo ${{ secrets.SECRET_SEED }} | sed 's/./& /g' 



# 제약사항
# 재사용할 수 있는 workflows에 대한 몇 가지 제약사항이 있습니다.

# - 재사용된 워크플로우는 재사용할 수 있는 워크플로우를 호출할 수 없습니다.
# - 앞에서 얘기한 대로 private 저장소의 재사용할 수 있는 워크플로우는 같은 저장소에서만 사용할 수 있다.
# - caller(호출하는 쪽) 워크플로우에 env 컨텍스트로 정의된 환경변수는 called(호출 받는 쪽) 워크플로우에 전달되지 않는다.
# - 재사용할 수 있는 워크플로우를 호출하는 잡에서 strategy 프로퍼티는 지원되지 않는다.
